// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyACa_AQoox_tUS8MXfaHFIBk4ukgNF2zoQ",
    authDomain: "benepick-7d89f.firebaseapp.com",
    projectId: "benepick-7d89f",
    storageBucket: "benepick-7d89f.firebasestorage.app",
    messagingSenderId: "165719448160",
    appId: "1:165719448160:web:cc3ea908b2bfbd135cc105",
    measurementId: "G-6XZM315ML3",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBidTo6zIzLWN5q8RR8CIDywb-Dk32Rqco", // "current_key" 값
    appId: "1:165719448160:android:eca1ac6bec969c3a5cc105", // "mobilesdk_app_id" 값
    messagingSenderId: "165719448160", // "project_number" 값
    projectId: "benepick-7d89f", // "project_id" 값
    storageBucket: "benepick-7d89f.firebasestorage.app", // "storage_bucket" 값
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyDIBJzWO7Cn3HOiaMWg6YYJyCsvfkW3q-o", // "API_KEY"
    appId: "1:165719448160:ios:a5cf506de8577d645cc105", // "GOOGLE_APP_ID"
    messagingSenderId: "165719448160", // "GCM_SENDER_ID"
    projectId: "benepick-7d89f", // "PROJECT_ID"
    storageBucket: "benepick-7d89f.firebasestorage.app", // "STORAGE_BUCKET"
    iosBundleId: "com.vn.benepick", // "BUNDLE_ID"
  );


}
