// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCma1lBaGJ_96iAKX5HKTS0AzcPLUBK-ig",
    authDomain: "vn-project-bed5c.firebaseapp.com",
    projectId: "vn-project-bed5c",
    storageBucket: "vn-project-bed5c.firebasestorage.app",
    messagingSenderId: "777692029381",
    appId: "1:777692029381:web:da6f14e4639bdd7581ebac",
    measurementId: "G-2ST1LMX4RS",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCma1lBaGJ_96iAKX5HKTS0AzcPLUBK-ig",
    appId: "1:777692029381:android:da6f14e4639bdd7581ebac",
    messagingSenderId: "777692029381",
    projectId: "vn-project-bed5c",
    storageBucket: "vn-project-bed5c.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyCma1lBaGJ_96iAKX5HKTS0AzcPLUBK-ig",
    appId: "1:777692029381:ios:da6f14e4639bdd7581ebac",
    messagingSenderId: "777692029381",
    projectId: "vn-project-bed5c",
    storageBucket: "vn-project-bed5c.firebasestorage.app",
    iosBundleId: "com.example.vnProject",
  );
}
